In [1]:
import torch

In [2]:
t= torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [3]:
t = t.cuda()
t

C:\Users\nagam\anaconda3\envs\tensorflow-\lib\site-packages\torch\cuda\__init__.py:116: UserWarning: 
    Found GPU0 GeForce GT 730 which is of cuda capability 2.1.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


tensor([1, 2, 3], device='cuda:0')

In [48]:
import pandas as pd
import numpy as np
import random 
import time
import gym
import random
from IPython.display import clear_output

In [49]:
env =gym.make("FrozenLake-v0")

In [50]:
action_space_size =env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [51]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [55]:
rewards_all_episodes=[]

#Q-learning algorithm
for episode in range(num_episodes):
    state=env.reset()
    
    done =False
    rewards_current_episode =0
    
    for step in range(max_steps_per_episode):
        
        #exploration-exploitaion trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action =env.action_space.sample()
        
        new_state,reward,done,info =env.step(action)
        
        #updateQ-table for(s,a)
        q_table[state,action] =q_table[state,action] *(1-learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state =new_state
        rewards_current_episode += reward
        
        if done ==True:
            break
        
        # Exploration rate decay
        exploration_rate = min_exploration_rate + \
            (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
        
        rewards_all_episodes.append(rewards_current_episode)

# #Calculation and print the avarage reward per thousand episodes
# rewards_per_thousand_episodes =np.split(np.array(rewards_all_episodes),num_episodes/100)
# count = 1000
# print("******************Average reward per thousand Episodes******************")
# for r in rewards_per_thousand_episodes:
#     print(count,":", str(sum(r/100)))
#     count += 1000

# #print updateed q-tadle
# print("\n\n***Q-table***\n")
# print(q_table)

In [53]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000


********Average reward per thousand episodes********

1000 :  0.0
2000 :  0.0
3000 :  0.0
4000 :  0.0
5000 :  0.0
6000 :  0.0
7000 :  0.0
8000 :  0.0
9000 :  0.0
10000 :  0.0


In [54]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.4941483  0.48272787 0.48350915 0.48378752]
 [0.41624411 0.36105005 0.24396908 0.46833354]
 [0.42620288 0.40830008 0.41892615 0.4555142 ]
 [0.40434277 0.27592064 0.3131773  0.44910107]
 [0.51727691 0.37199792 0.34289218 0.3848988 ]
 [0.         0.         0.         0.        ]
 [0.23384283 0.08884978 0.19485602 0.16943113]
 [0.         0.         0.         0.        ]
 [0.39243233 0.46237031 0.46511432 0.56790286]
 [0.55629959 0.6024022  0.37472487 0.39862653]
 [0.51417693 0.36505159 0.43667516 0.34434365]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.46926145 0.58687982 0.74975851 0.56527806]
 [0.72734151 0.89672996 0.73660651 0.73360556]
 [0.         0.         0.         0.        ]]
